src/Entity/Specialites.php
<?php

namespace App\Entity;

use App\Repository\SpecialitesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SpecialitesRepository::class)]
class Specialites
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $duree_consultation = null;

    #[ORM\Column]
    private ?float $tarif = null;

    #[ORM\ManyToOne(inversedBy: 'specialites')]
    private ?Blocs $id_bloc = null;

    #[ORM\Column(length: 255)]
    private ?string $statut = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDureeConsultation(): ?int
    {
        return $this->duree_consultation;
    }

    public function setDureeConsultation(int $duree_consultation): static
    {
        $this->duree_consultation = $duree_consultation;

        return $this;
    }

    public function getTarif(): ?float
    {
        return $this->tarif;
    }

    public function setTarif(float $tarif): static
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getIdBloc(): ?Blocs
    {
        return $this->id_bloc;
    }

    public function setIdBloc(?Blocs $id_bloc): static
    {
        $this->id_bloc = $id_bloc;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Form/SpecialitesType.php
<?php

namespace App\Form;

use App\Entity\Blocs;
use App\Entity\Specialites;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;

class SpecialitesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom',TextType::class,[
                'constraints'=>[
                    new NotBlank(),
                    new Assert\Length(['min'=>2,'max'=>100,'minMessage'=>'Veuillez entrer un nom valide min 3 et max 100'])
                ]
            ])
            ->add('description',TextType::class,[
                'constraints'=>[
                    new NotBlank(),
                    new Assert\Length(['min'=>2,'max'=>100,'minMessage'=>'Veuillez entrer un nom valide min 3 et max 100'])
                ]
            ])
            ->add('duree_consultation',IntegerType::class,[
                'constraints'=>[
                    new NotBlank(),
                    new Assert\Range([
                        'min'=>20,
                        'max'=>90,
                        'notInRangeMessage'=>'Veuillez entrer un nombre valide min 20 et max 90'
                    ])
                ]
            ])
            ->add('tarif',IntegerType::class,[
                'constraints'=>[
                    new NotBlank(),
                    new Assert\GreaterThan([
                        'value'=>39,
                        'message'=>'Veuillez entrer un nombre valide min 40'
                    ])
                ]
            ])
            ->add('statut', ChoiceType::class, [
                'choices' => [
                    'actif' => 'Actif',
                    'inactif' => 'Inactif',
                ]
            ])
            ->add('id_bloc', EntityType::class, [
                'class' => Blocs::class,
                'choice_label' => 'nom',
                'label' => 'Bloc&nbsp',
                'label_html'=> true
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Enregistrer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Specialites::class,
        ]);
    }
}

src/Controller/SpecialiteController.php
<?php

namespace App\Controller;

use App\Entity\Blocs;
use App\Form\SpecialitesType;
use App\Repository\BlocsRepository;
use App\Repository\SpecialitesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Specialites;

final class SpecialiteController extends AbstractController
{
    #[Route('admin/specialites', name: 'specialite.index')]
    public function index(SpecialitesRepository $repository,BlocsRepository $blocsRepository): Response
    {
        $specialites = $repository->findAll();
        $blocs = $blocsRepository->findAll();
        return $this->render('specialite/index.html.twig', [
            'specialites' => $specialites,
            'blocs' => $blocs,
        ]);
    }
    #[Route('/specialites', name: 'front.specialite.index')]
    public function indexfront(SpecialitesRepository $repository,BlocsRepository $blocsRepository): Response
    {
        $specialites = $repository->findAll();
        $blocs = $blocsRepository->findAll();
        return $this->render('specialite/front.html.twig', [
            'specialites' => $specialites,
            'blocs' => $blocs,
        ]);
    }
    #[Route('admin/specialite/add', name: 'specialite.create')]
    public function create(Request $request, SpecialitesRepository $repository, EntityManagerInterface $em): Response
    {
        $specialite = new Specialites();
        $form = $this->createForm(SpecialitesType::class, $specialite);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($specialite);
            $em->flush();
            return $this->redirectToRoute('specialite.index');
        }
        return $this->render('specialite/create.html.twig', [
            'specialite' => $specialite,
            'form' => $form->createView(),
        ]);
    }
    #[Route('admin/specialite/{id}/edit', name: 'specialite.edit', requirements: ['id'=>'\d+'])]
    public function edit(Request $request, Specialites $specialite, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(SpecialitesType::class, $specialite);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('specialite.index');
        }
        return $this->render('specialite/edit.html.twig', [
            'specialite' => $specialite,
            'form' => $form->createView(),
        ]);
    }

    #[Route('admin/specialite/{id}/delete', name: 'specialite.delete', requirements: ['id'=>'\d+'])]
    public function delete(Request $request, Specialites $specialite, EntityManagerInterface $em): Response
    {
        $em->remove($specialite);
        $em->flush();
        return $this->redirectToRoute('specialite.index');
    }

}

templates/specialite/create.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    {{ form(form) }}
{% endblock %}

templates/specialite/edit.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <h1>Edit Specialite</h1>
    {{ form(form) }}
{% endblock %}

templates/specialite/front.html.twig
{% extends 'base.front.html.twig' %}

{% block head %}
    <!-- Stylesheets -->
    <link href="front/mouhanned/css/bootstrap.css" rel="stylesheet">
    <link href="front/mouhanned/css/responsive.css" rel="stylesheet">
    <link href="front/mouhanned/css/style.css" rel="stylesheet">

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{% endblock %}
{% block content %}
<!--Service Section-->
<section class="service-section">
    <div class="container">
        <div class="section-title text-center">
            <h3>Our <span>Blocs</span></h3>
            <p>Tracking immunizations has never been easier or more secure with Florida SHOTS™. To print your child's <br>To print your child's record, you will needrecord, you will need</p>
        </div>
        <div class="sortable-masonry">
            <div class="filters text-center">
                <ul class="filter-tabs filter-btns clearfix">
                    {% for bloc in blocs %}
                        <li class="active filter" data-role="button" data-filter=".{{ bloc.nom }}"><div class="tab-btn"><i class="flaticon-medical"></i>{{ bloc.nom }}</div></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="row items-container clearfix">
                {% for spec in specialites %}
                <div class="col-md-4 col-sm-6 col-xs-12 masonry-item {{ spec.idBloc.nom}}">
                    <div class="inner-box">
                        <div class="image-content text-center">
                            <span>Capitalize on low hanging</span>
                            <a href="service-details"><h6>{{ spec.nom }}</h6></a>
                            <p>{{ spec.description }}</p>
                            <div class="link-btn">
                                <a href="service-details" class="btn-style-two">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
    <script src="front/mouhanned/js/jquery.js"></script>
    <script src="front/mouhanned/js/bootstrap.min.js"></script>
    <script src="front/mouhanned/js/bootstrap-select.min.js"></script>
    <script src="front/mouhanned/js/jquery.fancybox.pack.js"></script>
    <script src="front/mouhanned/js/jquery.fancybox-media.js"></script>
    <script src="front/mouhanned/js/html5lightbox.js"></script>
    <script src="front/mouhanned/js/isotope.js"></script>
    <script src="front/mouhanned/js/masterslider/masterslider.js"></script>

    <!-- revolution slider js -->
    <script src="/front/mouhanned/assets/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="/front/mouhanned/assets/revolution/js/extensions/revolution.extension.video.min.js"></script>

    <script src="front/mouhanned/js/owl.js"></script>
    <script src="front/mouhanned/js/owl.carousel.min.js"></script>
    <script src="front/mouhanned/js/validate.js"></script>
    <script src="front/mouhanned/js/jquery.appear.js"></script>
    <script src="front/mouhanned/js/jquery.countTo.js"></script>
    <script src="front/mouhanned/js/wow.js"></script>
    <script src="front/mouhanned/js/jquery-ui.js"></script>
    <script src="front/mouhanned/js/timePicker.js"></script>
    <script src="front/mouhanned/js/pie-chart.js"></script>

    <script src="front/mouhanned/js/script.js"></script>{% endblock %}

templates/specialite/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <a href="{{ path('specialite.create') }}">Add specialite</a>
    <table style="width:100% ; border: 1px">
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Duree consultation</th>
            <th>Tarif</th>
            <th>Status</th>
            <th>Bloc</th>
            <th>Action</th>
        </tr>
        {% for spec in specialites %}
            <tr>
                <th>{{ spec.id }}</th>
                <th>{{ spec.nom }}</th>
                <th>{{ spec.description }}</th>
                <th>{{ spec.dureeConsultation }}</th>
                <th>{{ spec.tarif }}</th>
                <th>{{ spec.statut }}</th>
                <th>{{ spec.idBloc.nom }}</th>
                <th>
                    <a href="{{ path('specialite.edit',{id: spec.id}) }}">Edit</a>
                    <a href="{{ path('specialite.delete' , {id: spec.id}) }}">Delete</a>
                </th>
            </tr>
        {% endfor %}
    </table>
{% endblock %}